Setup Liquibase [POL-30]
DataBiosphere/terra-external-credentials-manager pull request #1
Opened 2021-05-25 19:17 UTC by snwessel

2021-05-26 20:22 UTC, dvoet requested changes

2021-05-26 20:22 UTC, dvoet commented on src/main/resources/db/changelog/changesets/21052021_initial_schema.yaml
> +            sql: "CREATE TYPE token_type_enum AS ENUM ('document', 'code')"
I would call this `document_token` and `access_token` (or just `document` and `access` but plain `access` feels weird)

2021-05-26 20:22 UTC, dvoet commented on src/main/resources/db/changelog/changesets/21052021_initial_schema.yaml
> +                    nullable: false
need a unique constraint on these 2 together

2021-06-01 14:39 UTC, snwessel commented
I just updated the enum type names and added the unique constraint as suggested. When I ran the app, it created the constraint successfully! 
<img width="514" alt="image" src="https://user-images.githubusercontent.com/23193756/120342064-6db73080-c2c5-11eb-95da-02d923fb68ee.png">

2021-06-01 19:17 UTC, dvoet approved these changes

2021-06-01 19:18 UTC, merged