Parse json string input to string
DataBiosphere/terra-external-credentials-manager pull request #123
Opened 2022-04-06 17:48 UTC by yuhuyoyo

2022-04-06 18:36 UTC, ddietterich approved these changes
LGTM

2022-04-07 18:09 UTC, dvoet requested changes

2022-04-07 18:09 UTC, dvoet commented on service/src/main/java/bio/terra/externalcreds/controllers/SshKeyApiController.java
> +      String userEmail = new ObjectMapper().readValue(email, String.class);
There is a `ObjectMapper` spring bean, add it as a parameter to the `SshKeyApiController` record (see `OidcApiController`). Then use that instead of calling `new ObjectMapper()`

2022-04-07 18:09 UTC, dvoet commented on service/src/main/java/bio/terra/externalcreds/controllers/SshKeyApiController.java
> +      log.error("Failed to parse the email input");
don't log, this is not a system error

2022-04-07 19:49 UTC, dvoet approved these changes

2022-04-07 20:29 UTC, merged