Change passport response to text-plain
DataBiosphere/terra-external-credentials-manager pull request #141
Opened 2022-07-08 19:43 UTC by tlangs

2022-07-11 14:03 UTC, dvoet requested changes
apis should return json format

2024-01-03 20:41 UTC, tlangs commented
This endpoint does not return JSON. It returns a base64-encoded plaintext string.

2024-01-11 16:51 UTC, Ghost-in-a-Jar approved these changes

2024-01-11 17:06 UTC, Shakespeared approved these changes

2024-01-11 19:01 UTC, merged