Sw iz health
DataBiosphere/terra-external-credentials-manager pull request #5
Opened 2021-06-07 20:10 UTC by snwessel

Creating a basic health endpoint which checks for a valid database connection and returns an empty 200 response if everything is OK.

->  Created by @zarsky-broad and I

2021-06-08 15:20 UTC, dvoet requested changes
We should have a discussion about application layering but given this is simple I will let it slide for now. Fix the error codes please

2021-06-08 15:20 UTC, dvoet commented on service/src/main/java/bio/terra/externalcreds/PublicApiController.java
> +        return new ResponseEntity<>(HttpStatus.EXPECTATION_FAILED);
This should not be a 4xx level error. 4xx errors generally means the client did something wrong and can fix it. I think this should be INTERNAL_SERVER_ERROR. If we really want to distinguish this case from the one below I would suggest 503 but 503 is usually indicative of an apache proxy error so I don't recommend it. The real thing that we should use to distinguish the error condition is logging. Add some logging :)

2021-06-08 21:00 UTC, snwessel commented
@dvoet we added a more detailed 200 response (describing which subsystems we check) and updated the error response type. Before we implement logging, we were thinking that we should maybe talk as a group about how we want to set it up. Let us know what you think!

2021-06-09 13:26 UTC, dvoet approved these changes

2021-06-09 16:18 UTC, merged