Sw mock test configs
DataBiosphere/terra-external-credentials-manager pull request #78
Opened 2021-10-05 20:37 UTC by snwessel

I've been looking into test config mocking and came to a few conclusions:
1. It's not worth creating test utils for this because the config mocking is pretty simple to begin with. 
2. We often forget to mock the configs, so our unit tests often use the actual config values. To me, that seems like a weird dependency since we're testing the functions, not the configs.

The changes below create a separate set of configs which can be used by the tests. That way we don't need to remember to mock them every time they're relevant to a test.

2021-10-05 20:38 UTC, snwessel commented on service/src/test/resources/application.yml
> +    username: ${DATABASE_USER:ecmuser}
I haven't found a way to avoid including the `spring.datasource` definition here. If anyone has an idea of how to simplify this, let me know!

2021-10-05 21:48 UTC, Shakespeared approved these changes

2021-10-06 16:29 UTC, dvoet requested changes
I agree that the dependency between the production config and tests seems weird. But I think most tests don't actually care what the config is, i.e. they work for all config values. I think the tests that are sensitive to particular config values should have those values baked into the test itself to eliminate dependencies.

The benefit to loading production config in tests is that something in our test path actually does so and we know the config is valid. We could have a separate test just for that. If we add a required config value it would be great to catch in unit tests that a value is missing from prod config.

2021-10-06 16:29 UTC, dvoet commented on service/src/test/java/bio/terra/externalcreds/services/ProviderServiceTest.java
> -
I am concerned about removing this because the test cares about this value. Moving the value to application.yml creates a dependency that is hard to see.

2021-10-07 18:29 UTC, snwessel commented on service/src/test/java/bio/terra/externalcreds/services/ProviderServiceTest.java
> -
That makes sense, and I totally agree that it does create a dependency that's hard to see. I think that there are some issues with the way we're currently mocking (like how it's easy to forget to mock something and create a weird dependency), but I'm also not sure of a better solution for this right now, so I might just close this ticket and spend some more time thinking about it.

2021-10-07 18:30 UTC, closed without merging